### ISSUE TITLE
set_trace() not commented out

### ISSUE THREAD

**Issue by SPDermot** [credativUK/credativ-addons#25]
@craiggowing We found this yesterday and thought you should know

https://github.com/credativUK/credativ-addons/blob/addons-7.0/stock_queue_tasks/stock.py#L37

**Comment by craiggowing** [comment]
@SPDermot - Thanks for the heads up. Usually my git commit hooks stop me if I've left ipdb in!
Fixed in https://github.com/credativUK/credativ-addons/commit/74dbfbea8f511589bf0ad088072e125b55758a63
